config/routes.rb
Rails.application.routes.draw do

  resources :boost
  resources :task do
    member do 
      post 'text_boost' => "task#text_boost"
      post 'picture_boost' => "task#picture_boost" 
      post 'money_boost' => "task#money_boost"
      put  'stop_timer' => "task#stop_timer"
      put  'validation_end' => "task#validation_end"
    end
    collection do 
      get  "category" => "task#category"
    end
  end

  root 'welcome#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  get 'launchingpage' => 'static_pages#launchingpage'
  get 'about' => 'static_pages#about'  
  get 'terms' => 'static_pages#terms'

end

app/models/boosts/boost.rb
class Boost < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  validates :text, length: {maximum: 140}
  mount_uploader :image, ImageUploader 

end

app/models/boosts/money_boost.rb
class MoneyBoost < Boost
  validates :money, presence: :true


  def content
    "<h4>#{money / 100}$</h4>"
  end

end

app/models/boosts/picture_boost.rb
class PictureBoost < Boost
  validates :image, presence: :true

  def content
    "<img alt=\"boost_image\" src=\"#{image.thumb.url}\" />"
  end

end

app/models/boosts/text_boost.rb
class TextBoost < Boost
  validates :text, presence: :true


  def content
    "<h4>#{text}</h4>"
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :boosts
  validates :title, :start_date, :hour, :end_date, :presence => true
  validates :start_date, date: {equal_to: Date.today}, on: :create
  validates :end_date, date: {after_or_equal_to: (Date.today + 1), before_or_equal_to: (Date.today + 98)}, on: :create
  validates :hour, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 23}

  mount_uploader :validation_image, ImageUploader
  mount_uploader :cover_image, ImageUploader


  def time_before_end
    time_in_second = (DateTime.new(end_date.year, end_date.month, end_date.day, hour, 0, 0, '+2') - DateTime.now) * 1.day
    time_in_second > 0 ? time_in_second.to_i : 0
  end

  def transition_finished
    self.state = "finished"
    self.save
  end

  def transition_successful
    self.state = "successful"
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :login, :password, :avatar, presence: true
  validates :login, uniqueness: true
  # validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # validates :password, length: {minimum: 8}
  has_many :tasks
  has_many :boosts

  # validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include StripeCard
end

app/controllers/boost_controller.rb
class BoostController < ApplicationController
  before_action :set_boost, only: [:show]
  before_action :check_user

  def index
    @boosts = Boost.all
  end

  def show
  end

  private

  def check_user
    if current_user.nil?
      flash[:error] = "You need to login"
      redirect_to new_user_session_path
    end
  end

  def set_boost
    @boost = Boost.find(params[:id])
  end

  def boost_params
    params.require(:boost).permit(:content)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end
 
  #  specify their first and last names  when updating their profiles.
  # def account_update_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def launchingpage
		
	end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :set_task, :only => [:show, :text_boost, :picture_boost, :money_boost, :stop_timer, :validation_end]
  before_action :check_time_task, :only => [:show, :index]
  before_action :check_user

  def index
    @tasks = Task.where("state = ?", "ongoing")
    # @tasks = Task.all
  end

  def show
    @boost = Boost.new
  end

  def new
    @task = Task.new
  end

  def category
    @tasks =  Task.where("state = ?", params[:state])
  end


  def text_boost
    @boost = Boost.create(boost_params)
    if @boost.save
      @task.boosts << @boost
      current_user.boosts << @boost
      flash[:notice] = "your boost has been successfully sent"
    else
      flash[:error] = @boost.errors.full_messages.join(', ')
    end
    redirect_to @task
  end

  def picture_boost
    @boost = Boost.create(boost_params)
    if @boost.save
      @task.boosts << @boost
      current_user.boosts << @boost
      flash[:notice] = "your boost has been successfully sent"
    else
      flash[:error] = @boost.errors.full_messages.join(', ')
    end
    redirect_to @task
  end

  def money_boost
    begin
      StripeCard::charge_user(boost_params[:money], "eur", params[:stripeToken])
      @boost = Boost.create(boost_params)
      if @boost.save
        @task.boosts << @boost
        current_user.boosts << @boost
        flash[:notice] = "your boost has been successfully sent"
      else
        flash[:error] = @boost.errors.full_messages.join(', ')
      end
    rescue Exception => e
      flash[:notice] = e.message
    end
    redirect_to @task
  end

  def stop_timer
    if current_user == @task.user
      @task.transition_finished
      flash[:notice] = "The task has been stop"
    else
      flash[:error] = "your not the owner of the task"
    end
    redirect_to @task
  end

  def validation_end
    if current_user == @task.user && params[:image]
      @task.validation_image = params[:image]
      if @task.save
        @task.transition_successful
        flash[:notice] = "The task has confirmed"
      else
        flash[:error] = @task.errors.full_messages
      end
    else
      flash[:error] = "your not the owner of the task"
    end
    redirect_to @task
  end


  def create
    @task = Task.new(task_params)
    @task.hour = DateTime.now.hour
    @task.start_date = Date.today
    if @task.save
      flash[:notice] = "Task #{@task.title} succefully created"
      current_user.tasks << @task
      redirect_to @task
    else
      flash[:error] = @task.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def check_user
    if current_user.nil?
      flash[:error] = "You need to login"
      redirect_to new_user_session_path
    end
  end

  def check_time_task
    @tasks = Task.where("end_date <= ?", DateTime.now)
    @tasks.each do | task|
      if task.state != "successful"
        if task.end_date < Date.today
          task.transition_finished
        elsif task.end_date == Date.today && task.hour < DateTime.now.hour
          task.transition_finished
        end
      end
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :start_date, :end_date, :hour, :cover_image)
  end

  def boost_params
    params.require("boost").permit(:content, :text, :type, :image, :money)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :check_time_task, :only => [:index]

  def index
    @tasks = Task.where("state = ?", "ongoing").last(3)
  end

  private

  def check_time_task
    @tasks = Task.where("end_date <= ? AND state = 'ongoing'", DateTime.now)
    @tasks.each do | task|
      if task.state != "successful"
        if task.end_date < Date.today
          task.transition_finished
        elsif task.end_date == Date.today && task.hour <= DateTime.now.hour && DateTime.now.minute > 0
          task.transition_finished
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/boost/index.html.erb
<ul>
  <% @boosts.each do |boost|%>
    <li>
      <h2><%= boost.content %></h2>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booostme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application'%>
<!--   <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %> -->
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body cz-shortcut-listen="true">


  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to (image_tag("booostme_400vert.png", class: "logo")), root_path %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--<%= link_to "Booostme", root_path, :class => "navbar-brand" %>-->
       
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-left">
          <li><%= link_to "Create challenges",  new_task_path, class: "linknav"%></li>
          <li><%= link_to "All challenge",  task_index_path, class: "linknav"%></li>
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
              Category <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Ongoing challenges", category_task_index_path(:state => "ongoing"), :class => "btn btn-default", :role => "button" %></li>
              <li><%= link_to "Finished challenges", category_task_index_path(:state => "finished"), :class => "btn btn-default", :role => "button" %></li>
              <li><%= link_to "Succeeded challenges", category_task_index_path(:state => "successful"), :class => "btn btn-default", :role => "button" %></li>
            </ul>
          </li>
          <%= render 'devise/shared/login_items' %>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </nav>


  <div class="container-fluid page_content col-md-offset-1">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    <%= yield %>
      <footer>  
        <ul class="dsg-landing-list">
          <li>
            <%= link_to "About", about_path %>
          </li>
          <li>
            ©Booostme 2015
          </li>
        </ul>
      </footer>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
      $('[data-countdown]').each(function() {
        var $this = $(this), finalDate = $(this).data('countdown');
        $this.countdown(finalDate, function(event) {
          $this.html(event.strftime('%D days %H:%M:%S'));
        });
      });
    });
  </script>

</body>
</html>

app/views/static_pages/about.html.erb
 <div class="row" id="about">
  <div class="content_about">
   	<div class="container">
     <div class="text-center"><h1 class="about-title">About</h1></div>   
   </div>
  </div>
 </div>	

 <div class="row">
  <div class="container">
	<div class="content_terms">
			<p class="text_terms">We launched Booostme to motivate and encourage people to perform positively . Success for a school exam , achieving a professional task or success of a daily challenge is never done alone. We need the support of our family or friends. What if we expanded it supports the whole world ! Here is the mission Booostme.<br><br> 

      </p>
	</div>
  </div>
</div>

app/views/static_pages/launchingpage.html.erb
 <header class="coming_soon">
	<div class="row">
		<div class="text-center">
			<img src="assets/booostme_500vert.png" class="logo">
		</div>
			<div class="text-center">
        <h3 class="pitch">Encourage the world</h3>
      </div>
 </header>
<section>
  <div class="container">
     <div class="text-center">
      <h2 class="how">How it works</h2>
     </div>
        <div class="row" id="">
                    <blockquote class="col-md-4">
                        <cite>
                        	<div class="number">1</div>
                        </cite>
                        <p><b>Create a timed challenge and share it on twitter</b><br>
					 Painting the room of my newborn in 72 hours #booostmejrkinouani</p>
                    </blockquote>

                    <blockquote class="col-md-4" >
                        <cite>
                            <div class="number">2</div>
                        </cite>
                        <p><b>Get support from your friends tweets and around the world</b><br>
					Hi! more than 24 hours will go !	 by a support #hongkong ! #booostme</p>
                    </blockquote>

                    <blockquote class="col-md-4" cite="http://twitter.com/hwassner">
                        <cite>
                        	<div class="number">3</div>
                        </cite>
                        <p><b>Your challenge is successful,<br> tell the world to motivate !</b><br>
					 Yessss !!! I did two hours before the end ! :-) #booostme</p>
                    </blockquote>
      </div>
    </div>
  </section>
  <!--<aside>
  	 <div class="container">
        <div class="row">
        	<div class="text-center"><h2 class="faq">About us</h2></div>
        	<div class="text-center"><h3 class="about">We built Booostme with the idea of ​​motivating people to change the world.The change is never done alone, whether one is a charismatic leader or not. Can we imagine the march from Selma civil rights without its thousands of supporters ? Or success in school examinations without encouragement from relatives or friends ? The personal achievement in the positive, inspires, makes the world a better place and this is our mission.</h3></div>
        </div>
      </div>
   </aside>-->

<div class="row">
	<div id="footer">
    <div class="text-center"><a href="https://twitter.com/share" class="twitter-share-button" data-url="https://twitter.com/Booostmeapp" data-via="">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

        <a href="https://twitter.com/Booostmeapp" class="twitter-follow-button" data-show-count="false">Follow @Booostmeapp</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

      
      <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count">
      </div>

    </div>
  		  <span> © 2015 Booostme <%= link_to 'about', about_path %></span>
	</div>
</div>
	

app/views/static_pages/terms.html.erb
<div class="row" id="about">
  <div class="content_about">
   <div class="container">
     <div class="text-center"><h1 class="about-title">Terms of use</h1></div>   
   </div>
  </div>
</div>	

<div class="row">
  <div class="container">
	<div class="content_terms">
			<p class="text_terms">By using Booostme you are also subject to our Terms of Service. These Community Guidelines form part of the Life On Booostme Terms of Service and are incorporated.</p>
			<p class="text_terms"></p>
			<p class="text_terms">Booostme est ouvert toute personne âgé de 13 ans et plus.</p>
			<p class="text_terms">Vous pouvez envoyer des boosts à n'importe qui et recevoir des boost de n'importe qui.</p>
			<p class="text_terms">Les challenges crées se font dans l'unique but de motivier, d'encourager et d'inspirer les gens au bien.</p>
			<p class="text_terms">Il est interdit de créer des challenges liés à a violence, qui offense ou intimide autrui.</p>
			<p class="text_terms"></p>
			<p class="text_terms"></p>
			<p class="text_terms">Il est interdit de créer des challenges qui glorifie la posséssion d'armes à feux.</p>
			<p class="text_terms">Il est interdit de créer des challenges dont le sujet sont liés à l'univers du sexe ou qui touche à la séxualité.</p>
	</div>
  </div>
</div>

app/views/task/_boost_type.html.erb
<div class="row">
  <a href="#" role="tab" data-toggle="tab" class="col-md-4 boost_text_link" id="boost_text_link">
    <%= image_tag("pencil.png", :class => "img_booost") %>
    <p>Message</p>
  </a>
  <a href="#" role="tab" data-toggle="tab" class="col-md-4 boost_img_link" id="boost_img_link">
    <%= image_tag("picture.png", :class => "img_booost") %>
    <p>Photo</p>
  </a>
  <a href="#"  role="tab" data-toggle="tab" class="col-md-4 boost_money_link" id="boost_money_link">
    <%= image_tag("money.png", :class => "img_booost") %>
    <p>Money</p>
  </a>
</div>

<div style="display:none" class="row boost_text_form">
  <%= form_for(@boost, url: text_boost_task_path(@task), html: {method: :post}) do |f|%>
    <%= f.hidden_field :type, :value => "TextBoost" %>
    <div class="field">
      <%= f.label :text %><br />
      <%= f.text_area :text, autofocus: true, size: "24x6" %>
    </div>

    <div class="actions">
      <%= f.submit "send Boost", :class => "btn btn-lg btn-primary" %>
    </div>

  <% end %>
</div>

<div style="display:none" class="row boost_img_form">
  <%= form_for(@boost, url: picture_boost_task_path(@task), html: {method: :post, multipart: true}) do |f|%>
    <%= f.hidden_field :type, :value => "PictureBoost" %>
    <br/>
    <div class="field row">
      <div class="col-md-8 col-md-offset-2">
          <span class="file-input btn btn-block btn-primary btn-file">
              Choose File &hellip;  <%= f.file_field :image, :class => "file", :onchange => "readURL(this, 'img_prev_boost');"%>
          </span>
          <br />
      </div>
      <img id="img_prev_boost" class="img_preview" />
    </div>

    <div class="actions">
      <%= f.submit "send Picture", :class => "btn btn-lg btn-primary" %>
    </div>
  <%end%>
</div>

<div style="display:none" class="row boost_money_form">
  <%= form_for(@boost, url: money_boost_task_path(@task), html: {method: :post, id: "payment-form"}) do |f|%>
    <%= f.hidden_field :type, :value => "MoneyBoost" %>
    <span class="payment-errors"></span>

    <%= f.radio_button(:money, 100) %>
    <%= label_tag(:one_dollar, "$1") %>
    <%= f.radio_button(:money, 500) %>
    <%= label_tag(:five_dollar, "$5") %>
    <%= f.radio_button(:money, 1000) %>
    <%= label_tag(:ten_dollar, "$10") %>

    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input type="text" size="20" data-stripe="number" id="card_number" />
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>CVC</span>
        <input type="text" size="4" data-stripe="cvc" id="cvc"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Expiration (MM/YYYY)</span>
        <input type="text" size="2" data-stripe="exp-month" id="exp-month"/>
      </label>
      <span> / </span>
      <input type="text" size="4" data-stripe="exp-year" id="exp-year" />
    </div>

    <div class="actions">
      <%= f.submit "send money", :class => "btn btn-lg btn-primary" %>
    </div>
  <%end%>
</div>

app/views/task/_list_task.html.erb
<div class="row row-offcanvas row-offcanvas-right">
  <div class="col-xs-12 col-sm-12 dynamic">
    <div class="row">
      <% @tasks.each_slice(3) do | task_slice | %>
        <div class="row">
          <% task_slice.each do |task|%>
            <div class="col-xs-6 col-lg-3 item_task">
              <div class="row">
                <%= image_tag(task.cover_image.thumb) %>
              </div>
              <div class="item_task_content row">
                <div class="photo_profile_list">
                  <h2><%= task.title %></h2>
                  <p> Due date <%= task.end_date %></p>
                  <% if task.state == "ongoing" %>
                    <div class="countdown_timer_small" data-countdown="<%= task.end_date %> <%= task.hour%>:00"></div>
                  <%else%>
                    <div class="countdown_timer_small">TIME IS FINISH</div>
                  <%end%>
                  <p><%= link_to "View details", task_path(task), :class => "btn btn-default", :role => "button" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/task/_task_list_boost.html.erb
<h3>List of boost</h3>
<h4>Number of boost : <%= @task.boosts.count %> </h4>
<hr />
<% @task.boosts.order(created_at: :desc).each do |boost|%>
  <div class="row">
    <div class="col-md-2 img_profile_boost">
      <%= image_tag(boost.user.avatar.thumb) %>
    </div>
    <div class="col-md-5">
      <p>
        by <span class="login"><%= boost.user.login.capitalize %></span>
        <%= time_ago_in_words(boost.created_at) %>
      </p>
      <%= boost.content.html_safe%>
    </div>
  </div>
  <hr />
<% end %>

app/views/task/_user_task_information.html.erb
<h4>The challenger is :</h4>
<div class="row">
  <%= image_tag(@task.user.avatar.thumb) %>
</div>
<div class="row">
  <h4>Boost <%= @task.user.login.capitalize%> with:</h4>
</div>

app/views/task/category.html.erb
<%= render 'list_task' %>

app/views/task/index.html.erb
<%= render 'list_task' %>

<script type="text/javascript">
 
</script>

app/views/task/new.html.erb
 <div class="container task"> 
  <div class="text-center">
    <h3 class="baseline_titte">Booostme helps you get encouragement for successful your daily challenges</h3>
  </div>
  <div class="form-signin task">
    <h2 class="title_task">New task</h2>
    <%= form_for(@task, url: {action: "create"}, html: { method: :post, multipart: true }, :html => {:class => "form-horizontal"} ) do |f| %>
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title, autofocus: true, :class => "form-control" %>
      </div>
      <br />

      <div class="field">
        <%= f.label :end_date %><br />
        <%= f.text_field :end_date, autofocus: true, :class => "form-control datepicker" %>
      </div>

      <br />

      <div class="field">
        <%= f.label :cover_image %><br />
        <span class="file-input btn btn-block btn-primary btn-file">
          Choose File &hellip;  <%= f.file_field :cover_image, autofocus: true,:class => "file", :onchange => "readURL(this, 'img_prev_boost');" %>
        </span>
        <img id="img_prev_boost" class="img_preview" />
      </div>

      <div class="actions">
        <%= f.submit "Create", :class =>  "btn btn-lg btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({
                                  format: "dd/mm/yyyy",
                                  startDate: "<%= Date.today.strftime("%d/%m/%Y")%>",
                                  endDate: "<%= (Date.today + 98).strftime("%d/%m/%Y")%>",
                                  clearBtn: true,
                                  todayHighlight: true
                                });
  });
</script>

app/views/task/show.html.erb
<div class="col-md-2 item_show_task">
  <%=  render "user_task_information" %>
  <%=  render "boost_type" %>
</div>

<div class="col-md-6">
  <div class="row item_show_task">
    <h2><%= @task.title.capitalize %></h2>
    <p>By <%= @task.user.login %></p>
    <h3><%= @task.end_date.to_formatted_s(:long_ordinal) %></h3>
    <% if @task.time_before_end > 0 && @task.state == "ongoing" %>
    <div class="row">
      <div class="countdown_timer">
        <span id="getting-started"></span>
      </div>
    </div>
      <div class="row">
        <% if current_user == @task.user %>
          <%= link_to "Stop Timer", stop_timer_task_path(@task), :class => "btn btn-lg btn-danger stop_timer_button", :role => "button", method: :put %>
        <% end %>
      </div>
    <% else %>
      <h1>TIME IS FINISH </h1>
        <% if current_user == @task.user %>
          <%= form_for(@task, url: validation_end_task_path(@task), html: {method: :put,  multipart: true}) do |f|%>
            <div class="field row">
              <div class="col-md-4 col-md-offset-4">
                  <span class="file-input btn btn-block btn-primary btn-file">
                      Choose File &hellip;  <%= file_field_tag :image, :class => "file", :onchange => "readURL(this, 'img_prev');", id: "validation_image"%>
                  </span>
                  <img id="img_prev" class="img_preview" />
              </div>
            </div>
            <div class="actions row">
              <%= f.submit "Upload image", :class => "btn btn-lg btn-primary" %>
            </div>
          <%end%>
        <%end%>
    <%end%>
  </div>
  <div class="row item_show_task list_of_boost">
    <%= render 'task_list_boost' %>
  </div>
</div>

<div class="col-md-2 item_show_task">
  <div class="row ">
    <h4>Beginnig</h4>
    <div><%= image_tag(@task.cover_image.xxl, :class => "image_100_width") %></div>
  </div>
  <% if @task.state == "successful" %>
    <h4>End:</h4>
    <div class='row'>
      <div><%= image_tag(@task.validation_image.xxl, :class => "image_100_width")  %></div>
    </div>
  <%end%>
</div>

<script type="text/javascript">
  $("#getting-started").countdown("<%= @task.end_date%>" + " <%= @task.hour %>:00", function(event) {
    $(this).text(
      event.strftime('%D days %H:%M:%S')
    );
  }).on('finish.countdown', function(){location.reload()});


  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_umZbkFDV0vblJJX97EuGm9Su');
  // ...
  jQuery(function($) {
    $('#payment-form').submit(function(event) {
      var $form = $(this);

      // Disable the submit button to prevent repeated clicks
      $form.find('button').prop('disabled', true);

      Stripe.card.createToken($form, stripeResponseHandler);

      // Prevent the form from submitting with the default action
      return false;
    });
  });

  function stripeResponseHandler(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
    } else {
      // response contains id and card, which contains additional card details
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and submit
      $form.get(0).submit();
    }
  };
</script>


<script type="text/javascript">
  $(document).ready(function() {
    $(".boost_text_link").click(function(){
      $(".boost_text_form").show();
      $(".boost_img_form").hide();
      $(".boost_money_form").hide();
    });

    $(".boost_img_link").click(function(){
      $(".boost_text_form").hide();
      $(".boost_img_form").show();
      $(".boost_money_form").hide();
    });

    $(".boost_money_link").click(function(){
      $(".boost_text_form").hide();
      $(".boost_img_form").hide();
      $(".boost_money_form").show();
    });

  });
</script>

app/views/welcome/index.html.erb
<div class="menu_content">
  <div class="col-xs-12 col-sm-12 punchline">
    <%= image_tag("booostme_500vert.png", :class => "logo_content hidden-phone") %>
    <h2>Challenge yourself and be boosted <br> by the people around the world</h2>
    <div class="mobile-hide">
		<a class="btn btn--white btn--large" href="about.html" id="learn">
			Learn more
		</a>
	</div>
  </div>
</div>


<div class="row task_list">
  <div class="container">
   <h3>Featured</h3>
    <%= render 'task/list_task' %>
  </div>
</div>